### ISSUE TITLE
move the site to www.shineyoureye.org

### ISSUE THREAD

**Issue by mhl** [theyworkforyou/shineyoureye-sinatra#110]
There are a few steps here that we should do (not an exhaustive list - I might well have forgotten about some things!):

- [x] Re-use the `shineyoureye-sinatra` branch of https://github.com/mysociety/pombola_extract_info_pages/tree/shineyoureye-sinatra to update the prose repository with their latest blog posts
- [x] Create redirects for pages that might otherwise 404. We can't do 301 redirects from GitHub pages, but Google will also treat a `<meta http-equiv="refresh" ...>` tag as a redirect. In particular, we should:
    - [x] For the person route, switch to using Pombola slugs in the first place, falling back to EP UUIDs / CSV IDs (issue: https://github.com/theyworkforyou/shineyoureye-sinatra/issues/43)
    - [x] Try scraping all the URLs from the current site, and checking each of them against the new site to see if we've missed anything that can be helpfully redirected.
- [x] Once we've got the right contact email address from EiE, set that as `contact_email`
- [x] Image uploading fixes
- [x] Double check the DNS plan below makes sense :) <em>Update: Sam has suggested some changes below.</em>
- ~In https://github.com/theyworkforyou/shineyoureye-static/settings set the "Custom domain" to `www.shineyoureye.org`. (At the moment the site redirects `shineyoureye.org` -> `www.shineyoureye.gorg`, so let's keep that behaviour: https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/ )~
- ~Change the DNS entry for `shineyoureye.org` to be a A record for `theyworkforyou.github.io`'s IP address (GitHub pages seems to want it to be an A record [since this is an "apex domain"](https://help.github.com/articles/setting-up-an-apex-domain/) - the ANAME and ALIAS record types they referred to seem to be non-standard).~
- [x] Run `bin/deploy production`
- [x] Change the `travis.yml` in `shineyoureye-prose` to deploy to production instead of staging
- [x] Set the Github pages custom domain to `www.shineyoureye.org` to preserve the current forwarding behaviour (as described above and per the docs [here](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/);
- [x] Add `A` records for both `www.shineyoureye.org` and `shineyoureye.org` to our DNS pointing at `192.30.252.153` and `192.30.252.154` rather than the IP for `theyworkforyou.github.io` (see [this section](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) of the docs);
- [x] Add a DNS record for `pombola.shineyoureye.org` to our DNS pointing at pluto (`46.43.39.71`) and update the virtual host accordingly.
- <del> Add a Nagios check to see if the IP address of of theyworkforyou.github.io ever changes, since that'll break this site, and if we have a custom alert, we can provide a more helpful message for that than just the alert from the site being down.</del>
- [x] Create `pombola.shineyoureye.org` as a new A record for pluto and add that as a virtual host name for the old Pombola site (so it can be still used for editing contact details for people for the moment)
- [x] Make `pombola.shineyoureye.org` the primary name for the old Django vhost, so it doesn't just redirect to `www.shineyoureye.org`.
- [x] Create a new distinct staging site for our own testing and sharing new things with our partners (e.g. make deploying to production an option to `bin/deploy`)

**Comment by JenMysoc** [comment]
Issue for porting over the blogs is here: https://github.com/theyworkforyou/shineyoureye-sinatra/issues/111

**Comment by sagepe** [comment]
Based on a review of the docs and as discussed in Slack, I think that we'll need to adjust the DNS changes as follows. This is pretty close to the above, but differs in terms of the IPs to use for the two primary names.

- [ ] Set the Github pages custom domain to `www.shineyoureye.org` to preserve the current forwarding behaviour (as per the docs [here](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/);
- [ ] Add `A` records for both `www.shineyoureye.org` and `shineyoureye.org` to our DNS pointing at `192.30.252.153` and `192.30.252.154` rather than the IP for `theyworkforyou.github.io` (see [this section](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) of the docs);
- [ ] Add a DNS record for `pombola.shineyoureye.org` to our DNS pointing at pluto (`46.43.39.71`) and update the virtual host accordingly.

Given we'll be using the IPs provided by Github a Nagios check doesn't make much sense - we'll have nothing to compare against. I would expect them to announce any changes to these as given the non-standard nature of `ALIAS` and `ANAME` records they must be being used by many Github Pages users.

I see the TTL for the `shineyoureye.org.` zone is currently set to five minutes. We're using NOTIFY to push updates to slaves so shouldn't need to worry about the refresh TTL (it's currently set to a day).

**Comment by mhl** [comment]
:sparkles: Done! :tada:

**Comment by octopusinvitro** [comment]
Woooo!!!! :confetti_ball:

**Comment by octopusinvitro** [comment]
P.S. Remember to set the contact form!

https://github.com/theyworkforyou/shineyoureye-sinatra/pull/138
