### ISSUE TITLE
Allow users to email from the site

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#148]
EiE want to make all email addresses clickable to open up the users email clients and allow them to send emails to representatives.

Their ideal flow is click on email address, pop up window opens to write email with user's email service.

**Comment by octopusinvitro** [comment]
I think that is the default behavior of email links in browsers, since we are using `mailto:EMAILHERE` in the `href` attibute for emails.

Maybe they don't have their client configured for that? In that case there are some guides online to set it up:

* [For Firefox}(https://support.mozilla.org/t5/Manage-preferences-and-add-ons/Change-the-program-used-to-open-email-links/ta-p/1940)
* [For Chrome (if they use Outlook)](https://productforums.google.com/forum/#!msg/chrome/FngTaedzxWc/GwtjkmBfGtwJ)
* [Setting several browsers to open outlook](https://www.msoutlook.info/question/mailto-links-do-not-open-outlook)
