### ISSUE TITLE
Map EP person UUIDs to their Pombola slugs

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#43]
This is a WiP at the moment. The person URLs use the EP UUID as slug, so once we have the data we have to update this to use the Pombola slugs.

Remember to do #121 when this is merged

**Comment by mhl** [comment]
It's good to add some reasoning about why we'd want to do this to the ticket. For example, in this case it might be:
1. So that if we switch shineyoureye.org over to this new, static version, the basic person pages won't need to be redirected.
2. So that the URLs for people are shorter and more human readable

**Comment by octopusinvitro** [comment]
Closed in https://github.com/theyworkforyou/shineyoureye-sinatra/pull/125

**Comment by octopusinvitro** [comment]
Closed in #125
